### PR TITLE
Update theme.css

### PR DESCRIPTION
**Pull request by bellesea**
Fixing #18 — only worry with merging it is for people that are using a live version of the css theme will see changes without knowing why.

### CODE REVIEW

**Review by sampoder — COMMENTED** [review]
Hmm... this is an interesting, I think we could probably just have --font-6 be 64px? Otherwise, we could go through all of the GitHub repos that reference our CSS file

**Comment by bellesea** [comment]
> Hmm... this is an interesting, I think we could probably just have --font-6 be 64px? Otherwise, we could go through all of the GitHub repos that reference our CSS file

hmm... i looked through theme.hackclub.com, this new PR is the most accurate in terms of following it. but i think prior reliability is probably more important that this nuanced consistency?

**Comment by sampoder** [comment]
yeah, this matches theme.hackclub.com. there's probably not too much usage
of hackclub.css so we could go through and PR in patches

**Comment by garyhtou** [comment]
i think this may have taken down the website!

https://css.hackclub.com/

**Comment by sampoder** [comment]
this is bizarre... but yes it did

**Comment by sampoder** [comment]
Looks like a Vercel config issue that was only came it effect with new deployments. Fixed!

**Comment by garyhtou** [comment]
Homepage is back up!

The minified files are 404ing. Links [here](https://github.com/hackclub/css#accessing-the-stylesheets)

https://dash.hackathons.hackclub.com/hackathons/submissions/new is currently using the minified versions

**Comment by bellesea** [comment]
ack, thank you!

**Pull request merged**
