### PR TITLE
fix wavy bug

### PR DESCRIPTION
**Pull request by bellesea**

### CODE REVIEW

**Review by exu3 — APPROVED** [review]
LGTM!

(edit: oops didn't see the preceding review)

**Comment by bellesea** [comment]
> Ooooh @bellesea I didin't know about this attribute! Nice find 🕵️‍♀️ Would you mind posting a screenshot of what it looks like now?

sure :)
Screenshot 2022-03-14 at 10 54 34 PM

**Review by jessicard — APPROVED** [review]
Looks great @bellesea, merge away ⭐️

**Comment by bellesea** [comment]
> Looks great @bellesea, merge away ⭐️

wahoo! thanks :)

**Pull request merged**
